version: 0.2

phases:
  install:
    commands:
      - sudo yum update -y
      - curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
      - sudo yum install nodejs -y
      
  pre_build:
    commands:
      - echo Install dependencies
      - npm install
      - npm test

  build:
    commands:
      - echo Building for production
      - rm -rf node_modules
      - npm install --production

artifacts:
  files:
    - "**/*"
  name: CalculatorApp-$(date +%Y-%m-%d) 